### ISSUE TITLE
API additions

### ISSUE THREAD

**Issue by LukasKalbertodt** [LukasKalbertodt/stable-vec#3]
Things we probably want to add to the API:

- [x] a consuming iterator
- [x] `insert_at`
- [x] `FromIterator` impl
- [x] `into_vec()`
- [x] `contains()`
- [x] `Debug` impl
- [x] `Extend` impl
- [x] `Default` impl
- [x] `retain`
- [x] `insert_into_hole(index, elem) -> Result<(), Elem>`
- [x] `io::Write` impl for `StableVec<u8>`
- [x] ~~`From<Vec<T>>` impl~~ -> only possible with specialization. Instead `from_vec` was added.
- [x] Expose `next_index` or something like that to allow users to build iterators themselves

Things we might or might not want to add,  mostly because the semantics are not clear yet:

- [ ] `truncate(new_len)`
- [x] `clear()` (but what does it do exactly?)
- [x] `first()`, `first_mut()`, `last()`, `last_mut()` (but those would be O(n)!)
- [ ] `swap()` (invalidates two indices... uhm maybe?)

**Comment by burjui** [comment]
Besides #25, I am also willing to implement `IntoIter` and `insert_at`, if you're not working on it already.

**Comment by LukasKalbertodt** [comment]
@burjui Thanks for the offer. No I'm not working on either right now. You can certainly implement `insert_at` (in a new PR though), but I am not sure about `IntoIter` yet. 

This stuff is pretty tricky, I think. At least for `Vec<T>` the iterator is tricky because it has to make sure nothing is dropped twice, even in the case of a panic somewhere. However, I could be wrong and it's easy for `StableVec`. 

Another concern I have with `IntoIter` is that I am very unhappy with the current implementation. In the beginning I thought using a `Vec<T>` would be a good idea until I introduced two memory unsafety bugs :see_no_evil:  (#24). That's why I very much want to rewrite the internals, presumably even in a generic way so that the user can decide which representation to use (see #2). So if `IntoIter` would need any knowledge about the internals, I think it's not worth implementing it now. 

*However*, if you can implement `IntoIter` easily completely on top of the public `StableVec` API (without being less efficient than it could be), I'd be very happy to merge that!

**Comment by LukasKalbertodt** [comment]
Almost everything was implemented by now. I will close this large-scope issue now. Separate issues can be created for separate features. (Example #29)
